// RootLayout.js
import Navbar from "./components/ui/nav";
import { AuthProvider } from "./components/ui/AuthContext";
import "./globals.css";

export const metadata = {
    title: "POWER GYM",
    description: "Generated by create next app",
};

export default function Home({ children }) {
    return (
        <AuthProvider>
            <html lang="es">
                <head></head>
                <body className="bg-fondoPG">
                    <header>
                        <Navbar />
                    </header>
                    <main>{children}</main>
                </body>
            </html>
        </AuthProvider>
    );
}
