import Navbar from "./components/ui/nav";
import "./globals.css";


export const metadata = {
  title: "POWER GYM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
      </head>
      <body className="bg-fondoPG">
        <header>
          <Navbar />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
